name: Production Build
on:
  push:
    branches: [ master ]

env:
  APP_NAME: get_special_hole

jobs:
  docker:
    runs-on: ubuntu-latest
    working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@master

#      - name: Set up Go
#        uses: actions/setup-go@master
#        with:
#          go-version: 1.21.1
#
#      - run: go version
#      - name: Automated Testing
#        env:
#          MODE: test
#        run: go test -v -count=1 -json -tags release ./tests/...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:master
